# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mensagem_pb2 as mensagem__pb2


class MensagemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComunicacaoBidirecional = channel.stream_stream(
                '/mensagem.MensagemService/ComunicacaoBidirecional',
                request_serializer=mensagem__pb2.MensagemRequest.SerializeToString,
                response_deserializer=mensagem__pb2.MensagemResponse.FromString,
                )
        self.EnviarMensagem = channel.unary_unary(
                '/mensagem.MensagemService/EnviarMensagem',
                request_serializer=mensagem__pb2.MensagemRequest.SerializeToString,
                response_deserializer=mensagem__pb2.MensagemResponse.FromString,
                )


class MensagemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComunicacaoBidirecional(self, request_iterator, context):
        """Comunicação Bidirecional: Servidor e Cliente podem enviar mensagens simultaneamente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarMensagem(self, request, context):
        """Mantém compatibilidade com versão anterior
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensagemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComunicacaoBidirecional': grpc.stream_stream_rpc_method_handler(
                    servicer.ComunicacaoBidirecional,
                    request_deserializer=mensagem__pb2.MensagemRequest.FromString,
                    response_serializer=mensagem__pb2.MensagemResponse.SerializeToString,
            ),
            'EnviarMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensagem,
                    request_deserializer=mensagem__pb2.MensagemRequest.FromString,
                    response_serializer=mensagem__pb2.MensagemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mensagem.MensagemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MensagemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComunicacaoBidirecional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mensagem.MensagemService/ComunicacaoBidirecional',
            mensagem__pb2.MensagemRequest.SerializeToString,
            mensagem__pb2.MensagemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnviarMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensagem.MensagemService/EnviarMensagem',
            mensagem__pb2.MensagemRequest.SerializeToString,
            mensagem__pb2.MensagemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
