# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensagem.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensagem.proto\x12\x08mensagem\" \n\x0fMensagemRequest\x12\r\n\x05texto\x18\x01 \x01(\t\"$\n\x10MensagemResponse\x12\x10\n\x08resposta\x18\x01 \x01(\t2Z\n\x0fMensagemService\x12G\n\x0e\x45nviarMensagem\x12\x19.mensagem.MensagemRequest\x1a\x1a.mensagem.MensagemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagem_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MENSAGEMREQUEST']._serialized_start=28
  _globals['_MENSAGEMREQUEST']._serialized_end=60
  _globals['_MENSAGEMRESPONSE']._serialized_start=62
  _globals['_MENSAGEMRESPONSE']._serialized_end=98
  _globals['_MENSAGEMSERVICE']._serialized_start=100
  _globals['_MENSAGEMSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
